export type UserType = {
    id: string ;
    userName: string;
    bussinesName: string;
    email: string;
    phoneNumber: string;
    businessName: string;
    minOrder: number;
    isActive: boolean;
    roleId: string;
    isPopular: boolean | null;
    isPharmacy: boolean;
    region: string;
    regionId?: string;
    accountid?: string;
    orderNum?: number;
    MinOrder?: number;
    action: React.ReactNode;
    roles?: { id: string; roleId?: string; name?: string }[];
};